### ISSUE TITLE
status change

### ISSUE THREAD

**Issue by ZoltanBrindza** [dbweb-ch/ioBroker.tesla-motors#56]
I m interested in the timing of the change of state.This happens at minute intervals.When the action is performed via the mobile app,it s take 1 minute for it to manifest itself in iobroker.It is possible to change the minute timing?20s?How can I see it in real time?
Thank you

**Comment by dbweb-ch** [comment]
If the car is moving or was moving in the last 10 minutes, the refresh time is 5 seconds.
Otherwise it has to be lower. If it would refresh all the time, the car would never fall asleep. If the car does not go to sleep he will take ~5% of your battery within 24h, so really a lot.
If you really need it more often you could use "aggressive" as refresh rate. This is currently set to 60s, but I think I will change that to 1s in the next version.

**Comment by ZoltanBrindza** [comment]
Thank you for answer
Smart car tracking is good for  me and when the car sleeps everything is ok,but when the car doesn t sleep it would be well clocked to reduce from 60S to 5s approximately

**Comment by dbweb-ch** [comment]
yes, I think you are right. I will set refresh down to 5 seconds if car is awake and down to ~ 1s if car is driving.

**Comment by dbweb-ch** [comment]
just commited this to the master, you are free to test it out.

**Comment by ZoltanBrindza** [comment]
I tried and it s a same 60s

**Comment by dbweb-ch** [comment]
You did install it from the master? I tried it on my own, and it is down to 5 seconds, and down to 1 second when car is running.

**Comment by ZoltanBrindza** [comment]
What it means the master?Can you help me with that?

**Comment by ZoltanBrindza** [comment]
I already found it,thank you,it works perfectly.It s around 6-8s👍👍👍
