### ISSUE TITLE
Adapter doesn't update values anymore

### ISSUE THREAD

**Issue by trollvottel** [dbweb-ch/ioBroker.tesla-motors#61]
Hey, since I installed v0.4.2, the adapter stops updating values after some time.

This is my log output, the car was in use and awake from 8:25 to 9:13 (according to TeslaLogger). Somehow the adapter doesn't update anything anymore.

I guess the adapter must check regularly in shorter intervals, if the car is awake **without actually waking it up** (The Tesla App homescreen widget does that as well).

tesla-motors.0 | 2021-04-19 09:13:29.662 | debug | (36291) system.adapter.admin.0: logging true
-- | -- | -- | --
tesla-motors.0 | 2021-04-19 08:20:15.770 | debug | (36291) Check for Tokens and Expires
tesla-motors.0 | 2021-04-19 08:20:15.770 | debug | (36291) Checking if token is valid
tesla-motors.0 | 2021-04-19 07:20:15.763 | debug | (36291) Check for Tokens and Expires
tesla-motors.0 | 2021-04-19 07:20:15.762 | debug | (36291) Checking if token is valid
tesla-motors.0 | 2021-04-19 06:20:15.757 | debug | (36291) Check for Tokens and Expires
tesla-motors.0 | 2021-04-19 06:20:15.756 | debug | (36291) Checking if token is valid

**Comment by dbweb-ch** [comment]
The Adapter checks this regulary (every few seconds). But as documented, there can be a glitch of 15 minutes while the adapter tries to let the car fall asleep. If you request additional information within these 15 minutes, the car resets it's timer to go asleep and therefore will never go asleep. This is caused by tesla and there is nothing I can do against it.

**Comment by trollvottel** [comment]
@dbweb-ch Did you see the timestamps of the log? There are more than 3 hours in-between where the car has been used but the adapter did not recognize it. "TeslaLogger" btw. did, though.
