### ISSUE TITLE
Temporary adjustment refresh rate?

### ISSUE THREAD

**Issue by and-web** [dbweb-ch/ioBroker.tesla-motors#84]
Don't know if this is technically possible, but I see a very common use case where it would be great to have the adapter temporarily in the "aggressive" refresh rate, but just for a small period of time.

When driving, the "speed" and "power" values change so rapidly that the "smart" refresh rate is just way too slow to make a useful visualization of consumption graphs over time.

By introducing 0.4.3, the refresh rate in the "aggressive" mode has been changed to one second which would enable users to visualize speed and power much more accurately. Leaving aggressive turned on permanently however would lead to massive battery drain.

Since iobroker seems not to offer a possibility to change adapter details by a script, do you see the chance of an object which can be used to temporarily change the refresh rate? Many thanks for your outstanding dedication to this project, which means a lot to me. Cheers!

**Comment by dbweb-ch** [comment]
Which Version do you have installed? 
The Refresh rate is much higher since 0.4.3 in all modes. When the car is awake it is 5 Seconds, and if the car is moving 1 Second. So the adapter calls, waits for answer and after getting the answer, waits just 5 or 1 second for the next call. Bare in mind, that this also depends on the internet connection of the car. If you drive trough regions with bad mobile coverage, this won't work. The call can be made and it can take several seconds until the car responds.
So actually the "smart" method should do exactly what you need, and still let the car fall asleep when not moving around.
